sort_string:sort_string_main.o sort_string.o

sort_string_main.o:sort_string_main.c sort_string.h sort_string.c

sort_string.o:sort_string.c sort_string.h

.PHONY:
clean:
	rm sort_string.o sort_string_main.o

